---
shardul:
  :name: Shardul Sardesai
  :bragwords: Curious developer, Foodie, Adventurer
  :coverpic: 
  :profilepic: 
  :twitter: tmp
  :linkedin: https://linkd.in/lionsardesai
  :facebook: https://www.facebook.com/lionsardesai
  :googleplus: https://plus.google.com/lionsardesai
  :email: shardul@ssardesai.com
  :id: shardul
sushrut:
  :name: Sushrut Sardesai
  :bragwords: Wanderer, Photographer
  :coverpic: 
  :profilepic: 
  :twitter: 
  :linkedin: 
  :facebook: https://www.facebook.com/sardesai.sushrut
  :googleplus: 
  :email: sardesai.sushrut@gmail.com
  :id: sushrut
apurva:
  :name: Apurva (Appy) Bhave(-Sardesai)
  :bragwords: almost Ph.D, Herbs, Aquaponics, Food, 
  :coverpic: 
  :profilepic: 
  :twitter: 
  :linkedin: https://www.linkedin.com/in/apurvabhave/
  :facebook: 
  :googleplus: 
  :email: apsy09@gmail.com
  :id: apurva
