# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fed016bf13f9cfa1a01e0ac3427aecef095eee4035a9edd4b72a1bf0a0a22b662d8dd8346127405250ed083f525dd2d003ea192b9ab944e8b021235c3c67a23

test:
  secret_key_base: 5abab38ec1e77b72ec6af3cb4820b6afa824d8aaa41fabe13aae1f971370362c8996f84c17ec48f6f81c076a91fb8ba93012f0e2faf567e8b65cbd3ce4cd4e9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
